### ISSUE TITLE
Suspected pathing issues with non-English locale characters in file path

### ISSUE THREAD

**Issue by dashodanger** [edge-classic/EDGE-classic#341]
[debug.txt](https://github.com/dashodanger/EDGE-classic/files/9954631/debug.txt)

I have attached the debug log for a user who is encountering issues launching the game. The user had a clean install and confirmed that the files reported missing in the log were indeed present. Will update as progress is made.

**Comment by andwj** [comment]
Yeah, Russian letters in the username.

**Comment by dashodanger** [comment]
I've pushed https://github.com/edge-classic/EDGE-classic/commit/9ace336dcfdf997f69591096b624341e8d6d6fde as a hopeful fix for this issue. I'll wait to close this until we get a chance to test with various users/locales

**Comment by dashodanger** [comment]
I've pushed an update to the pathfix branch to try to help with the args/params that contain paths as well, https://github.com/edge-classic/EDGE-classic/commit/a31547ed3dd36ba5721a3d72172d91135de5d20f

**Comment by dashodanger** [comment]
Closing now that https://github.com/edge-classic/EDGE-classic/pull/369 has been merged into master; paths and program arguments should now be recognized correctly even if containing non-ASCII characters
