### ISSUE TITLE
Boom wall scrollers

### ISSUE THREAD

**Issue by simc2** [edge-classic/EDGE-classic#385]
Hi, congrats for adding support for Boom displacement and accelerative scrollers. 

However, with Boom wall scrollers 249, 218 and 254 the walls won't always move to the direction where they should.

249 scroll tagged wall when control sector height changes
218 accelerate tagged wall when control sector height changes
254 scroll tagged wall, the action line sets the speed and direction

Here's a test wad for Doom2 map01 with 249 scrollers. There are four switches to scroll the opposite walls. All sets are otherways identical except roteted by 45/90 degrees. All the walls should have the same scrolling result. The arrows indicate in which direction each part of the wall should move.

[boom_249_scroller.zip](https://github.com/edge-classic/EDGE-classic/files/10526954/boom_249_scroller.zip)

An other concern is that the walls desync. Although in this case the 249 lines are in a lift which will return to it's original height the walls do gain a small offset change in the process.

**Comment by dashodanger** [comment]
I'm not really sure why the walls in your demo WAD don't move in the way you expect. I used PrBoom + the BOOMEDIT.wad example on /idgames as the reference for whether or not they move in the right direction. In the case of BOOMEDIT.wad, there is identical behavior as far as direction. I do notice the slight offset desync and will look at that, but for the direction issue I don't have much to go off of at the moment.

**Comment by dashodanger** [comment]
Quick update...looking at BOOMEDIT.wad, I think I built the original implementation in such a way that it happened to work if the control and target lines were either parallel, perpendicular, or at a 45 degree angle to each other. I'm working on a fix that implements the proper rotation.

**Comment by dashodanger** [comment]
As of https://github.com/edge-classic/EDGE-classic/commit/a5d41d4311dc7dcb0daa14b95fdab3df9be44d10, as far as I can tell, both the angle rotation of the scrollers and the offset misalignment have been fixed. Please feel free to comment/ask for it to be re-opened if more cases are observed where this isn't true. I really appreciate the test map you provided...this was huge in being able to properly troubleshoot it.
