### ISSUE TITLE
Consider using SDL_GetPrefPath to set where Edge writes files 

### ISSUE THREAD

**Issue by pbdot** [edge-classic/EDGE-classic#409]
Edge writes files and directories into the current binary folder, which is problematic for a number of reasons. 

Using [SDL_GetPrefPath](https://wiki.libsdl.org/SDL2/SDL_GetPrefPath) could be a solution to this, with org and app names being configurable, preferably with some app metadata, though could be at compile time.

**Comment by dashodanger** [comment]
Agreed; I think doing it program-wide would address the macOS packaging issue as well. I'll start tinkering with it.

**Comment by dashodanger** [comment]
https://github.com/edge-classic/EDGE-classic/actions/runs/4316738150 here's a first crack at it for testing

**Comment by pbdot** [comment]
This is great, I did make one comment in the recent commit, though isn't related to the functionality.
