### ISSUE TITLE
Issues with Boom displacement and accelerative scrollers

### ISSUE THREAD

**Issue by simc2** [edge-classic/EDGE-classic#437]
Hi, the Boom displacement and accelerative scrollers (scroll/accelerate when control sector's height changes) do not always work right.

The examples from Boomedit.wad do work right. In those the control sector is always a lift; the scrolling or acceleration starts when the lift is lowered/scrolled back or deaccelerated when the lift returns back. But for other type of control sector movements the results are mixed.

Here's a test wad for Doom2 map01. It has ten scrolling tracks with different setups of control sectors. In all tracks when the A-switch is triggered the medikit should scroll away from the player. On displacement scrollers the srolling should stop when the control sector stops moving. One accelerative scrolers the scrolling should continue. When the B-switch is triggered the medikits should scroll back or the scrolling should deaccelerate and stop to a stand still.

https://www.dropbox.com/s/ckil8870o6m1jxp/scrollers.zip?dl=1

**Comment by dashodanger** [comment]
As of https://github.com/edge-classic/EDGE-classic/commit/af081a058a77ea0172d18e03d1bd3b27213e4e26, the scrollers should now exhibit the behavior described in the text file attached to your map. Thanks again!
