### ISSUE TITLE
trying to run edge-classic.exe v1.4

### ISSUE THREAD

**Issue by KappesBuur** [edge-classic/EDGE-classic#463]
https://imgur.com/7lb2jX7

runs okay in v1.21

**Comment by dashodanger** [comment]
This was a result of upgrading the AJBSP codebase that we are using internally. It has been fixed as of https://github.com/edge-classic/EDGE-classic/commit/eff9d58549edefb3a66367875d035c6e81edad13, which will be available in the next release.
