### ISSUE TITLE
Can't configure mouse sensitivity with reasonable precision

### ISSUE THREAD

**Issue by GrayFace** [edge-classic/EDGE-classic#465]
If I set any non-integer mouse sensitivity in EDGE config, it rounds it to an integer. This makes it impossible to get anywhere near proper sens.

**Comment by dashodanger** [comment]
https://github.com/edge-classic/EDGE-classic/pull/467 has now been merged into the master branch and should bring the functionality that you describe. All settings tied to sliders are now stored as floating-point values. These values can manually be set (via console/config CVAR) to values outside of the range that the sliders can accommodate as well, if necessary.
