### ISSUE TITLE
Some Edge issues with boomedit!.wad

### ISSUE THREAD

**Issue by hawkwind3** [edge-classic/EDGE-classic#486]
The screenshots show the problem and how it should look like as shown in a screenshot from doomretro
![boomedit](https://github.com/edge-classic/EDGE-classic/assets/35204218/027d9a74-21e7-4033-82e7-543dc66208d2)
![boomedit2](https://github.com/edge-classic/EDGE-classic/assets/35204218/13f78efb-8a45-464f-b80e-55f95312eb7f)
![correct](https://github.com/edge-classic/EDGE-classic/assets/35204218/9eeba7e8-7f44-42bf-bb30-7b228dfa807c)

pic 2 is when standing on risen stair sector 43.

**Comment by dashodanger** [comment]
Boom Line 242 has been extremely problematic for our engine and renderer, and although we have made great strides in compatibility for it compared to EDGE 1.35, it is likely that occasional aesthetic issues will be present for the foreseeable future. At this time, it is not a priority.

**Comment by dashodanger** [comment]
Better late than never but I've landed https://github.com/edge-classic/EDGE-classic/pull/751 to try to address these and other concerns.
