### ISSUE TITLE
Floor and ceiling changers

### ISSUE THREAD

**Issue by simc2** [edge-classic/EDGE-classic#500]
With the Boom generalized floor and ceiling changers the numeric and trigger modes seem to be swapped. If the line trigger is set up to use the numeric mode it currently uses the trigger mode instead and vice versa. This happens with the Boom generalized actions only. Regular Doom/Boom actions such as in Doom E2M1 do use the correct modes.

However it also seems that all numeric mode changers take the sector behind the highest numbered 2s line as the target when it should be the sector behind the lowest numbered 2s line instead. Full explanation on lines 356-359 in here: https://github.com/fragglet/mbf/blob/master/boomref.txt?plain=1#L358

And if the tagged floor or ceiling is at the target height already the texture and type are not changed.

Here's a test wad for Doom2 map01.
[floor+ceilingchangers.zip](https://github.com/edge-classic/EDGE-classic/files/11709620/floor%2Bceilingchangers.zip)

**Comment by dashodanger** [comment]
Thank you (again) for the excellent test map and documentation; while I try to work this I have a quick question. Do you know of any PWADs "in the wild" off the top of your head where this effect can be observed? I've made the mistake before of assuming everything was good because it works in an example WAD (like BOOMEDIT for instance) but fails in the "real world"

**Comment by simc2** [comment]
I stumbled on this by accident on my own (complevel 9 minimum) map. 
Saturnine Chapel does use Boom generic floor changers in it's round floor cyberdemon fight.
https://www.doomworld.com/idgames/levels/doom2/Ports/s-u/satchap

As with the Doom/Boom regular triggers only the 
- 177/159/84/37 Floor lower to lowest floor, change texture _and type_
- 78/241/240/239 Floor change texture and effect to nearest
- (191/9/155/146 Floor raise donut lower pillar)

use the numeric mode. With the probably most common types 37 and 9 I'd assume it's likely quite rare if there are several different flats or sector types at the target height. Though it's not impossible.

**Comment by dashodanger** [comment]
As of https://github.com/edge-classic/EDGE-classic/commit/18d4745e899a3d832230c2793f37b88dc0efa9c5, I think all of your concerns have been fixed. There were basically four issues at hand:
1 - As you suggested, the Boom generalized special processing was correctly identifying the model but assigning the opposite behavior.
2 - When looking for an appropriate surrounding sector, the linedefs that comprise a sector were being iterated through in reverse order and returning the first 'match'. This resulted in the highest (numerically) linedef being returned. They will now be iterated through in the order that they were assigned to the sector, which should result in the first matching linedef being the lowest index.
3 - From what I can tell by looking at the existing codebase, Tx0 and Tx changer types were never implemented. It seems like the assumption was that either both texture and type were changed or that nothing was changed.
4 - Changers already at the height of the target sector were never being executed. Our lifetimes and creation of plane movers differs a bit from Boom's thinkers in this regard and has always caused a bit of friction.
