### ISSUE TITLE
Awakening of monster spawner's monsters

### ISSUE THREAD

**Issue by simc2** [edge-classic/EDGE-classic#515]
Not fully sure of this but it looks like that monsters spawned by the monster spawner ignore if the player has fired a weapon in the area. 

Here's a test wad for Doom2 MAP01. The player is in a west side room and the monster spawner is in the east behind a window. The spawned monsters will appear in the middle and always face direction 0 to the east.
[monsterspawner.zip](https://github.com/edge-classic/EDGE-classic/files/12197946/monsterspawner.zip)

If the player shoots the pistol the monster spawner awakes. In vanilla Doom all the spawned monsters start chasing the player right from the start was player in sight or not. In Edge Classic the spawned monsters start to chase only if the player is in sight (in the moment of monster's appearance) or makes more noise. If the player is not in sight the spawned monsters just stand still.

If the monster spawner is awakened silently by player going to the window it works the same way both in vanilla Doom and in Edge Classic.  When the player hides away from the window the spawned monsters stand still and won't wake up if the player comes back to the window.

**Comment by LoboEire** [comment]
This is expected behaviour for EDGE-Classic. 
We moved to a more mobj-centric sound system to support new features like the HEAR_DISTANCE and NOISE_ALERT ddf commands. We decided at the time that it was worth any minor compatibility issues like this one.
