### ISSUE TITLE
Teleporter zipping

### ISSUE THREAD

**Issue by dashodanger** [edge-classic/EDGE-classic#561]
Easier to understand by seeing in-action, but teleporting things appear to be visible as they are moved to their new location, causing it to have a "zipping" effect

**Comment by LoboEire** [comment]
Same behaviour seen in EDGE 1.35, so not something we broke at least

**Comment by dashodanger** [comment]
Fixed with https://github.com/edge-classic/EDGE-classic/commit/34d807740e50deb071cf6b0833df0b0ad4aada12
