### ISSUE TITLE
Animate default intro graphic

### ISSUE THREAD

**Issue by dashodanger** [edge-classic/EDGE-classic#595]
Would be fun but also in the pause betwen the intro graphic and the first title/music playing it would help avoid the impression that something is locked up or delayed

**Comment by LoboEire** [comment]
What about using the one from the demo map?

**Comment by dashodanger** [comment]
Oh yeah, we should give that a shot.

**Comment by dashodanger** [comment]
Forgot to close this out, Lobo handled this with https://github.com/edge-classic/EDGE-classic/pull/605
