### ISSUE TITLE
file_c::ReadText allocation optimization

### ISSUE THREAD

**Issue by pbdot** [edge-classic/EDGE-classic#612]
file_c::ReadText allocates a local std::string which is returned and then copied to a new string in assignment.  It would be better to pass a std::string reference to receive the value

**Comment by dashodanger** [comment]
Tested solution in https://github.com/edge-classic/EDGE-classic/commit/d099c538a895b86ff8e89c058f6ba639b24af39e with Godbolt, and NVRO appears to correctly handle the situation
