### ISSUE TITLE
Doom 1: Intermission screen scaling does not take into account misc graphics

### ISSUE THREAD

**Issue by LoboEire** [edge-classic/EDGE-classic#647]
The intermission screen scaling does not apply correctly to the small animated graphics on the Ultimate Doom intermission screens.

**Comment by dashodanger** [comment]
Closing with https://github.com/edge-classic/EDGE-classic/commit/08419f7f94edce283f62e95bb7cc3ddb031f64dc

Stretch and Zoom scaling options removed per internal discussion
