### ISSUE TITLE
Music Issues on macOS

### ISSUE THREAD

**Issue by atsb** [edge-classic/EDGE-classic#65]
Hi,

I noticed you're using glatter (which is not compatible with Macs).  Currently it is now impossible to build a Mac version.

I suppose this change is permanent?

**Comment by dashodanger** [comment]
I like using it on the Window/Linux side, but if that's the case, at a minimum I can pull the prior GLEW contents and have them as the build option for Mac. I'm working through some other stuff on my local repo, but I'll add a comment to this thread when it has been restored.

**Comment by dashodanger** [comment]
https://github.com/dashodanger/EDGE-classic/commit/dd22ba86bbd5d431c9ab0214a98e77970312b67d should hopefully have GLEW restored properly when building for Mac. I may try exploring other GL loaders that could work across all platforms, or maybe even just return to having GLEW as the only solution. I'll keep this open until I hear that it's working.

**Comment by atsb** [comment]
Thanks very much :) works fine (with a patch).

Mac Patch:
vm_hud.cc

```
#if defined _MSC_VER || defined __APPLE__
#include <cmath>
#endif
```

std::ceil is in cmath.h and Apple machines need this to compile.

**Comment by atsb** [comment]
One slight issue I have now observed.  Music does not play on Mac.

**Comment by dashodanger** [comment]
I did change some of the recent filesystem functions...I wonder if it's not 'finding' the default soundfont now. Do internal MP3/OGG lumps still play with PWADs that have them?

**Comment by atsb** [comment]
Do you know any that contain those lumps?  I don't think I've played any pwads that have those lumps except on ZDoom specific wads with module music.

**Comment by dashodanger** [comment]
I usually use the Harmony IWAD, since the title and first level are MP3 at least.

**Comment by atsb** [comment]
I'll get on this tonight, just keeping this updated.

**Comment by dashodanger** [comment]
I renamed the issue to reflect the current situation; did you ever have a chance to try out MP3/OGG music?

**Comment by atsb** [comment]
I did yes, sorry I forgot to mention it here.  That is currently fine, I'll check it once every few months to check that nothing gets broken with it.

**Comment by dashodanger** [comment]
> I did yes, sorry I forgot to mention it here. That is currently fine, I'll check it once every few months to check that nothing gets broken with it.

Sounds good...as of commit https://github.com/dashodanger/EDGE-classic/commit/fe68d3aea24fb0203d85b3c44b6decd3ea90400f, I tweaked the function for locating the default soundfont to account for the home directory location instead of just being a pure relative path. Next time you end up trying, will you let us know if that did the trick, or if there's any log messages indicating what might be failing?

**Comment by atsb** [comment]
Well I've been trying out 1.1..  music does not play at all on a mac now.  Even the default Doom midi, nothing.  Only sound effects.

**Comment by dashodanger** [comment]
> Well I've been trying out 1.1.. music does not play at all on a mac now. Even the default Doom midi, nothing. Only sound effects.

I did a goof a did "home_dir" instead of "game_dir", forgetting that on non_Windows those are sometimes distinct locations. 
https://github.com/dashodanger/EDGE-classic/commit/625d45c02e9b7e72ee16b464ffbb1ee497f0cc21 should at least correctly look for the soundfont relative to the directory the executable as in. This fixed the issue when I encountered it on my Pi; I'll test on a Mac when I can.

**Comment by atsb** [comment]
I'll test it later so I'll probably beat you to it :)

**Comment by atsb** [comment]
This still happens.

**Comment by dashodanger** [comment]
Shoot, alright then...I'll update this when I have another inkling of what might be happening.

**Comment by dashodanger** [comment]
Going to close this out for inactivity and the fact that the current codebase is very different from when this issue first arose. If it's still happening on Mac, I can reopen it.

**Comment by atsb** [comment]
I'll give it a test and let you know

**Comment by dashodanger** [comment]
> I'll give it a test and let you know

Sounds good...actually, if it doesn't work would you mind opening a new issue? I forgot that this initially started as a Glatter vs. GLEW issue and it might be confusing for others
