### ISSUE TITLE
Retain Chex Quest 1 support in addition to Chex 3 Vanilla

### ISSUE THREAD

**Issue by MelodicSpaceship** [edge-classic/EDGE-classic#707]
Hi, developer of Chex 3 Vanilla here. I think it's pretty cool that you decided to add explicit support for it in this source port.

However, I would suggest retaining support for the original 1996 version of Chex Quest as well, as there are a small handful of PWADs that rely on it, and support for it would be needed to properly play them.

**Comment by dashodanger** [comment]
Appreciate the feedback; I think pulling CQ1 back from the commit history won't be too bad. The main check we use for CQ1/3 versus, say, Ultimate Doom is the actual verbiage within the ENDOOM lump so having those games tracked separately shouldn't be too difficult. I'll keep this open until it's back.

**Comment by MelodicSpaceship** [comment]
Great! Also, I'm not sure if this should be a separate issue, but Chex 3 Vanilla has an alternate IWAD with the filename chex3d2.wad called the "modding version" or "Chex Quest 3 for Vanilla Modding". It uses the Doom 2 format and shares most of the same resources with chex3v.wad but only contains dummy levels, as it's only intended as a base for PWADs.

Do you have any plans to support that as well?

**Comment by dashodanger** [comment]
That looks like it wouldn't be hard to handle as well; what we'd likely do is once the ENDOOM screen for CQ3V is identified, check whether E1M1 or MAP01 is found in the same WAD to determine which one it is exactly. I'll try to roll that up into the same commit.

**Comment by dashodanger** [comment]
As of https://github.com/edge-classic/EDGE-classic/commit/5572aa7eed5358bd7f45c801ab985dd3d8cf355a, Chex Quest 1, Chex Quest 3: Vanilla, and the modding version should be recognized as separate IWADs and have their resources loaded accordingly. I can leave this open if you'd like to fetch the latest and test as well, or close it if you're ok.

**Comment by MelodicSpaceship** [comment]
It looks pretty good so far, though I have a few more suggestions.

- The "wimap0" graphic in the "edge_base/chex3v/graphics/" folder is the incorrect graphic, as this was subtly changed between Chex 1 and Chex 3 Vanilla. "edge_base/chex3vm/graphics/" has the correct graphic, so it can be copied from there.
- Chex 3 Vanilla and the modding version still use the Chex Quest 1 story text screens, which were also changed in Chex 3 Vanilla. This is less noticeable in the former as the UMAPINFO overrides it anyways but the latter doesn't have a UMAPINFO lump.
- It would be nice if Chex 3 Vanilla's `TITLE_GRAPHIC` definition was changed to `"TITLEPIC","CQ1TITLE","CQ2TITLE","ENDPIC","VICTORY2"`, as this matches how it is in ZDoom and is closer to the original ZDoom version of Chex Quest 3, though the modding version shouldn't be changed in this regard.
- Both the primary and modding version of Chex 3 Vanilla have the same name in the game selection dialog, so it's hard to tell which is which when both are present. The modding version should be given a different name.
- Selecting "Chex Quest 1" from the game selection dialog gives an error saying `Assertion 'after[0]' failed (EDGE-classic-master/source_files/dehacked/deh_text.cc:469).` Specifying `-iwad chex.wad` on the command line instead still works.
- All 3 supported Chex Quest games have a red damage flash instead of a green one. This should be changed if possible.

**Comment by dashodanger** [comment]
I'm still working on these, but for the life of my I can't get the assertion error that you report to happen...I'm using the download off of DSDArchive; is there a different source/version for CQ1?

**Comment by MelodicSpaceship** [comment]
Hmm, I'm pretty sure I have the same version of CQ1. Maybe it's specific to the OS I use? I'm running it off of Linux Mint Debian Edition 6, in case that information helps.

**Comment by dashodanger** [comment]
I think I've addressed your latest accuracy/improvement concerns; I can also trigger the assertion error when trying to load one of the .deh files separately. I think this is an issue happening with external .deh files at the moment and not specifically CQ1/3, but I need to do some more testing.

**Comment by MelodicSpaceship** [comment]
I think this is just about done! One additional thing I've noticed is that the main version of Chex 3 Vanilla is missing the "Read This!" option in the main menu. But I think this can just be closed after that's addressed, and any additional things that need to be fixed regarding Chex Quest can just be opened as separate issues instead.

Also, I like how you added Chex 3 Vanilla's friendly larvae to Chex Quest 1.

**Comment by dashodanger** [comment]
I just pushed a tweak to "Read This!" detection; since both the "Doom 1" and "Doom 2" help image lumps are present in CQ3V's resources, this has the side effect of CQ3V: Modding Edition having a "Read This!" menu now, but there's not much that can easily be done outside of revamping how this is handled for all games. Since the menu displays properly for both CQ3V versions, I will go ahead and close this.

I really appreciate your help in getting this as correct as possible; it can be difficult to adapt new IWADs to EC because:
a) The tables that most ports modify with Dehacked don't actually exist in EDGE (patches are converted to DDF prior to usage)
b) Under the hood, every supported game is a "Doom mod", even Heretic.

I'll probably be making some future tweaks, but these are EC-specific things like dynamic light colors, etc.
