### ISSUE TITLE
[feature request] may be possible to uncap to 144fps or more?

### ISSUE THREAD

**Issue by Sol1vaN** [edge-classic/EDGE-classic#738]
responding from:
https://forum.zdoom.org/viewtopic.php?p=1255352#p1255352

your question:
"Is the 70 FPS target causing some kind of deficiency?"

answer:
yes, because the gamplay is choppy, feels stuttering and the most people have 120hz or more displays.

your observation:
"We saw the benefits of raising the original limit of 35 FPS, but it's unclear what investing time in more framerate targets would accomplish"

my opinion:
based on testing many others source ports, is very notyceable playing at more than 60fps, or in this case, 70fps is much more enjoyable.
EDGE is a impressive source port, but it will be nice this option can be added, that's why i'm want this on EDGE.

well, i hope you can.
i know touching the timetics engines, are very very complicated.
i know because dhewm3 have a lot of problems with this.
well, see ya and thanks for this great sourceport.

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme

you may need to install the c compiler

**Comment by Sol1vaN** [comment]
hmm...
https://www.youtube.com/watch?v=ImFNqYXrvdI

**Comment by dashodanger** [comment]
Those statements were indeed accurate at the time they were posted; since then, we have added things like the web player which also benefit from having uncapped frames. This has already been implemented in the main repository as of https://github.com/edge-classic/EDGE-classic/pull/734 and will be present in the next release.

**Comment by Sol1vaN** [comment]
thanks! a very good news!
i'll stay tuned when you release it. 😉
