### ISSUE TITLE
How to create edge_defs.epk

### ISSUE THREAD

**Issue by btclinux** [edge-classic/EDGE-classic#747]
Hi! There is no mention about it in COMPILING.md. I know it work with edge_defs directory, but would happy to pack it as in release

**Comment by dashodanger** [comment]
The shortest answer is "zip the contents of the edge_defs folder into a file called edge_defs.epk". 

If you want to do it via CLI there is some simple tar syntax in https://github.com/edge-classic/EDGE-classic/blob/master/cmake/EDGEClassic.cmake that might help as well.

**Comment by btclinux** [comment]
Thank you!
